version: "3.1"

services:
  nginx:
    build: ./nginx/
    ports:
        - 80:80
    links:
        - php
    volumes:
        - app
    networks:
        uln:
         ipv4_address: 10.6.0.2

  php:
    build: ./php/
    expose:
        - 9000
    links:
        - mysql
    volumes:
        # - app
        - ./php/php-hr-system:/var/www/html/
    networks:
        uln:
         ipv4_address: 10.6.0.3

  app:
    image: php:7.2-fpm
    volumes:
        - ./php/php-hr-system:/var/www/html/
    command: "true"

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - 3306:3306
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: webprog 
        MYSQL_USER: webprog 
        MYSQL_PASSWORD: webprog
    networks:
        uln:
         ipv4_address: 10.6.0.4

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql
    networks:
        uln:
         ipv4_address: 10.6.0.5

networks:
    uln:
     ipam:
        config:
         - subnet: 10.6.0.0/16

