security:
    # uncommnet to enable encoder
    encoders:
        App\Entity\User:
            #algorithm: argon2i
            algorithm: plaintext

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        memory_provider:
            # provider type - one of the above
            memory:
                # custom options for that provider
                users:
                    user:  { password: '%env(USER_PASSWORD)%', roles: [ 'ROLE_USER' ] }
                    admin: { password: '%env(ADMIN_PASSWORD)%', roles: [ 'ROLE_ADMIN' ] }
        chain_provider:
            chain:
                providers: [memory_provider, app_user_provider]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                provider: app_user_provider
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path:   logout


            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/user, roles: ROLE_ADMIN }
         - { path: ^/start, roles: ROLE_USER }
         - { path: ^/personal/data, roles: ROLE_HR }
         - { path: ^/job/data, roles: ROLE_HR }
         - { path: ^/adres, roles: ROLE_HR }
         - { path: ^/emails, roles: ROLE_HR }
         - { path: ^/engagement, roles: ROLE_HR }
         - { path: ^/membership, roles: ROLE_HR }
         - { path: ^/phone/numbers, roles: ROLE_HR }
         - { path: ^/staff/category, roles: ROLE_HR }
         - { path: ^/units, roles: ROLE_HR }


    role_hierarchy:
        ROLE_HR: ROLE_USER
        ROLE_ADMIN: ROLE_HR

